### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by jachym** [jachym/pywps-4#15]
PyWPS is able to work with major WPS clients, such as QGIS WPS client and OpenLayers

_add_more_here_

**Comment by SiggyF** [comment]
Here are some clients that I'm aware of:

In use:
- https://github.com/geopython/OWSLib (python)
- https://github.com/boundlessgeo/wps-gui

Legacy:
- http://dev.openlayers.org/examples/wps-client.html

In progress:
- https://github.com/OSGeo/ows.js

Discontinued:
- https://github.com/52North/uDig-WPS-plugin

**Comment by jachym** [comment]
This is long therm task. Tested with OWSLib recently and seems to be working.

**Comment by jachym** [comment]
Closing for lack of concrete issue
