### ISSUE TITLE
Input/Output classes in app.py missing inheritance

### ISSUE THREAD

**Issue by Noctalin** [jachym/pywps-4#39]
app.LiteralOutput
app.ComplexInput
app.LiteralInput

are not inheriting from the ones found in inout.py

**Comment by jachym** [comment]
As said before: I did not come to this sofar. Idea was to move them out
from app and make them little bit more robust

Thanks for the cleaning

po 9. 3. 2015 v 16:23 odesílatel Calin Ciociu <notifications@github.com>
napsal:

**Comment by Noctalin** [comment]
So should they be moved completely out of the app.py?
The current classes in app.py have mostly methods for returning elementmaker and the actual functionality is in inout.py.

**Comment by jachym** [comment]
+1 for removing from app.py



po 16. 3. 2015 v 13:01 odesílatel Calin Ciociu <notifications@github.com>
napsal:
