### ISSUE TITLE
Reference inputs not being treated

### ISSUE THREAD

**Issue by ldesousa** [jachym/pywps-4#44]
The app.get_input_from_xml function is not checking for References. It needs to look for a block like:
'./wps:Reference'

Does the data need to be fetched here in this method? Or it will be fetched later?

**Comment by jachym** [comment]
IMHO it does not matter where it's fetched, as long as it's provided by PyWPS itselve. 

IMHO separate "fetcher" class should be done (maybe we could introduce parallel fetching in the future for more inputs?)
