### ISSUE TITLE
Reference files

### ISSUE THREAD

**Issue by Noctalin** [jachym/pywps-4#46]
Create output as files if specified as reference.
Create file for the status document.

Output folder and URL are set in the configuration of PyWPS

**Comment by jachym** [comment]
Hi,
looking at the demo: seems, that the process is responsible for data downloading. 

That is IMHO wrong - downloading the data should be provided by PyWPS itself - also during the download, maximal file size and file type check (pywps/validator) shall be used

**Comment by Noctalin** [comment]
I didn't mention it in my post but yes I actually do the fetching now inside PyWPS and not in the process.
The demo needs a bit of fixing anyway.

Validators are used for inputs only correct?
