### ISSUE TITLE
Abstract attribute of a WPS service missing

### ISSUE THREAD

**Issue by geoslegend** [jachym/pywps-4#70]
When calling printInputOutput function on owslib.wps module, the error was occurred as follows:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/owslib/wps.py", line 1364, in printInputOutput
        print '%s identifier=%s, title=%s, abstract=%s, data type=%s' % (indent, value.identifier, value.title, value.abstract, value.dataType)
AttributeError: 'Input' object has no attribute 'abstract'
```

**Comment by geoslegend** [comment]
The abstract parameter in OGC WPS 1.0.0 document is not mandatory. I don't think that pywps-4 should consider the abstract parameter. However, in order to test the pywps-4 demo using OWSLib, it will need to be considered that in the pywps-4 demo files in the future.
[link to WPS 1.0.0 document](http://portal.opengeospatial.org/files/?artifact_id=24151)

**Comment by geoslegend** [comment]
The dataType parameter should be considered to be added into pywps-4 because an error is occurred on OWSLib:

```
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/root/.spyder2/.temp.py", line 24, in <module>
    printInputOutput(process)
  File "/usr/lib/python2.7/dist-packages/owslib/wps.py", line 1364, in printInputOutput
    print '%s identifier=%s, title=%s, abstract=%s, data type=%s' % (indent, value.identifier, value.title, value.abstract, value.dataType)
AttributeError: 'Process' object has no attribute 'dataType'
```

**Comment by jachym** [comment]
Hi,

as you are writing, abstract is not mandatory - therefore, I consider this as bug in owslib

I'll have a look on the data_type - it's used all around pywps-4, hard to tell, why owslib does not like it

**Comment by jachym** [comment]
@geoslegend could you please specify, how does your Process definition look like (give me code snippet, so I could test it?) Everything seems to be more or less working with OWSLib-master branch. I've made some changes though https://github.com/geopython/OWSLib/pull/304

**Comment by geoslegend** [comment]
@jachym sorry but I don't have source codes when I saw such errors. Today I had tested some syntax from my memory but I couldn't perform such errors again using OWSLib 0.10.3 and PyWPS 4 (downloaded on Dec. 23, 2015). So, if I see such errors again, I would send you the source codes,  development environments and etc.

**Comment by jachym** [comment]
OK, closing for now, feel free to reopen again. 

Thanks
