### ISSUE TITLE
ComplexData Parsing Error

### ISSUE THREAD

**Issue by geoslegend** [jachym/pywps-4#73]
I used that two ComplexInput parameters are JSON formats. PyWPS parsed the first parameter but not the second parameter. 

I guess that get_inputs_from_xml function in app/WPSRequest.py have some issues related to ComplexData parsing. Especially, _get_rawvalue_value function called in line 278 should be modified to be able to get the data by encoding condition such as base64.

* simple sample data 
{
  "plot" {
    "Version" : "0.1"
  }
}

**Comment by geoslegend** [comment]
I have modified _get_rawvalue_value function as follows:

def _get_rawvalue_value(data, encoding=None):
    """Return real value of CDATA section"""

    try:
        if encoding is None or encoding == "":
            return data
        else:
            return base64.b64decode(data)
    except:
        return data

**Comment by jachym** [comment]
@geoslegend I hope, the fix  works for you as well https://github.com/jachym/pywps-4/commit/c15f6b2d5db3dbea5dc60b5811f3b5e9bc195960

I'm closing this issue (feel free to re-open, if not working for you)
