### ISSUE TITLE
TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by geoslegend** [jachym/pywps-4#74]
mime_type function has an error in inout/formats/__init__.py as follows:

```
  File "D:\dev\python27_64\lib\site-packages\pywps-4.0-py2.7.egg\pywps\inout\formats\__init__.py", line 94, in mime_type
    formatdef = getattr(FORMATS, mime_type)
TypeError: getattr(): attribute name must be string
```

So, I think the second parameter of getattr function should be modified as follows:

```
    formatdef = getattr(FORMATS, 'mime_type')
```

**Comment by jachym** [comment]
@geoslegend could you specify more the use case, when this is occurring? At this place `mime_type` variable should be string containing anything from `pywps.inout.formats._FORMATS` tuple, which means  `GEOJSON, JSON, SHP, GML, GEOTIFF, WCS, WCS100, WCS110, WCS20, WFS, WFS100, WFS110, WFS20, WMS, WMS130, WMS110, WMS100`

What is your mime_type variable then and how did this happen?

**Comment by geoslegend** [comment]
@jachym The output format of response is JSON format and I implemented as follows:

'''
response.outputs['result'].output_format = Format(FORMATS.JSON)
'''

The error function is

'''
    @mime_type.setter
    def mime_type(self, mime_type):
        """Set format mime type
        """
        try:
            # support Format('GML')
            formatdef = getattr(FORMATS, mime_type)
            self._mime_type = formatdef.mime_type
        except AttributeError:
            # if we don't have this as a shortcut, assume it's a real mime type
            self._mime_type = mime_type
'''

The mime_type parameter printed:

'''
FormatDefintion(mime_type='application/json', extension='.json', schema=None)
'''

So, I think this issue is the syntax error of getarr function.

**Comment by jachym** [comment]
IMHO either

```
response.outputs['result'].output_format = Format(**FORMATS.JSON._asdict())
```
or
```
response.outputs['result'].output_format = FORMATS.JSON
```
should work

are you quoting from some code inside current pywps-4 code base?

thanks 

J

**Comment by geoslegend** [comment]
Both of two ways have been tested successfully based on PyWPS 4 (downloaded on JAN 02 2015 08:30 UTC +9:00). 

Thanks.

Q

**Comment by jachym** [comment]
ok, thanks a lot for your feedback, closing now (feel free to reopen, if I misunderstood something)
