### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by jachym** [jachym/pywps-4#8]
Format
======
* ConfigParser
* JSON

ConfigParser
-----------------
* Plain text
* Simple
* "Standard"
* PyWPS < 4 uses it

JSON
--------
* Plain text
* Can be structured
* Can apply json-schema
* PyWPS < 3 used it

What needs to be configured
=======================

server
--------
* title
* abstract
* fees
* keywords
* language
* max operations
* output
* logging
* database

provider
-----------
* company
* administrator's name
* position and role
* address
* phone
...

External plugins
---------------------
Mapserver, GeoServer, PostgreSQL/PostGIS, FTP, DropBox, GRASS GIS, ....

**Comment by Noctalin** [comment]
Should one of both be used?
Either ConfigParser or JSON, or both of them?
Otherwise I would have just taken the ConfigParser which seems to be doing a good job in PyWPS 3

**Comment by jachym** [comment]
+ 1  for config parser - it's easier to read by humans and still reproducable using code

**Comment by jachym** [comment]
Done and working, closing
